// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcUtilities.proto

package grpc.services.utilities;

public interface HeatPowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utilities.HeatPowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool hpower = 1;</code>
   */
  boolean getHpower();
}
