// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcUtilities.proto

package grpc.services.utilities;

public interface LightSettingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utilities.LightSettingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 setting = 1;</code>
   */
  int getSetting();
}
