// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcUtilities.proto

package grpc.services.utilities;

public interface LightPowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utilities.LightPowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lpower = 1;</code>
   */
  boolean getLpower();
}
