// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcUtilities.proto

package grpc.services.utilities;

public final class UtilitiesServiceImpl {
  private UtilitiesServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_LightPowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_LightPowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_LightPowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_LightPowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_HeatPowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_HeatPowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_HeatPowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_HeatPowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_LightSettingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_LightSettingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_LightSettingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_LightSettingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_HeatTempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_HeatTempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_HeatTempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_HeatTempResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023grpcUtilities.proto\022\tutilities\"#\n\021Ligh" +
      "tPowerRequest\022\016\n\006lpower\030\001 \001(\010\"$\n\022LightPo" +
      "werResponse\022\016\n\006lpower\030\001 \001(\010\"\"\n\020HeatPower" +
      "Request\022\016\n\006hpower\030\001 \001(\010\"#\n\021HeatPowerResp" +
      "onse\022\016\n\006hpower\030\001 \001(\010\"&\n\023LightSettingRequ" +
      "est\022\017\n\007setting\030\001 \001(\005\"\'\n\024LightSettingResp" +
      "onse\022\017\n\007setting\030\001 \001(\005\"\037\n\017HeatTempRequest" +
      "\022\014\n\004temp\030\001 \001(\005\" \n\020HeatTempResponse\022\014\n\004te" +
      "mp\030\001 \001(\0052\337\002\n\020UtilitiesService\022Q\n\020switchL" +
      "ightPower\022\034.utilities.LightPowerRequest\032" +
      "\035.utilities.LightPowerResponse\"\000\022Y\n\022adju" +
      "stLightSetting\022\036.utilities.LightSettingR" +
      "equest\032\037.utilities.LightSettingResponse\"" +
      "\000(\001\022N\n\017switchHeatPower\022\033.utilities.HeatP" +
      "owerRequest\032\034.utilities.HeatPowerRespons" +
      "e\"\000\022M\n\016selectHeatTemp\022\032.utilities.HeatTe" +
      "mpRequest\032\033.utilities.HeatTempResponse\"\000" +
      "0\001B1\n\027grpc.services.utilitiesB\024Utilities" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_utilities_LightPowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_utilities_LightPowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_LightPowerRequest_descriptor,
        new java.lang.String[] { "Lpower", });
    internal_static_utilities_LightPowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_utilities_LightPowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_LightPowerResponse_descriptor,
        new java.lang.String[] { "Lpower", });
    internal_static_utilities_HeatPowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_utilities_HeatPowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_HeatPowerRequest_descriptor,
        new java.lang.String[] { "Hpower", });
    internal_static_utilities_HeatPowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_utilities_HeatPowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_HeatPowerResponse_descriptor,
        new java.lang.String[] { "Hpower", });
    internal_static_utilities_LightSettingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_utilities_LightSettingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_LightSettingRequest_descriptor,
        new java.lang.String[] { "Setting", });
    internal_static_utilities_LightSettingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_utilities_LightSettingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_LightSettingResponse_descriptor,
        new java.lang.String[] { "Setting", });
    internal_static_utilities_HeatTempRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_utilities_HeatTempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_HeatTempRequest_descriptor,
        new java.lang.String[] { "Temp", });
    internal_static_utilities_HeatTempResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_utilities_HeatTempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_HeatTempResponse_descriptor,
        new java.lang.String[] { "Temp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
