// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcNews.proto

package grpc.services.news;

public final class NewsServiceImpl {
  private NewsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsPowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsPowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsPowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsPowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsStreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016grpcNews.proto\022\004news\"\"\n\020NewsPowerReque" +
      "st\022\016\n\006npower\030\001 \001(\010\"#\n\021NewsPowerResponse\022" +
      "\016\n\006npower\030\001 \001(\010\"$\n\021NewsStreamRequest\022\017\n\007" +
      "content\030\001 \001(\t\"%\n\022NewsStreamResponse\022\017\n\007c" +
      "ontent\030\001 \001(\t2\232\001\n\013NewsService\022D\n\017switchNe" +
      "wsPower\022\026.news.NewsPowerRequest\032\027.news.N" +
      "ewsPowerResponse\"\000\022E\n\nstreamNews\022\027.news." +
      "NewsStreamRequest\032\030.news.NewsStreamRespo" +
      "nse\"\000(\0010\001B\'\n\022grpc.services.newsB\017NewsSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_news_NewsPowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_news_NewsPowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsPowerRequest_descriptor,
        new java.lang.String[] { "Npower", });
    internal_static_news_NewsPowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_news_NewsPowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsPowerResponse_descriptor,
        new java.lang.String[] { "Npower", });
    internal_static_news_NewsStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_news_NewsStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsStreamRequest_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_news_NewsStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_news_NewsStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsStreamResponse_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
