// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcNews.proto

package grpc.services.news;

public interface NewsStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:news.NewsStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
