// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcNews.proto

package grpc.services.news;

public interface NewsPowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:news.NewsPowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool npower = 1;</code>
   */
  boolean getNpower();
}
